test_horizon: 50
lr: 0.0001
x_dim: 567
y_dim: 63
sigma_eps: 0.05

data_horizon: 50
num_class_samples: 40

nn_layers: [128,128,128]
activation: 'tanh'

# step params:
step_min: -2.5
step_max: 2.5
num_steps: 3

num_input_points: 10
num_hand_points: 21
input_dim: 3
shuffle: False