data_horizon: 20
test_horizon: 10
row_length: 30
meta_batch_size: 128    # Number of trajectories that are sampled
x_dim: 567      # For the space formulation. In this case x_dim = (num_input_points - 1) * num_hand_points * input_dim. (If we want the time formulation, set x_dim=1.)
y_dim: 63       # For the space formulation. In this case y_dim = 1 * num_hand_points * input_dim. (If we want the time formulation, set y_dim=63.)
sigma_eps: 0.005

lr: 0.0001
nn_layers: [256]
activation: 'tanh'
basis: 'lstm'

num_input_points: 10
num_hand_points: 21
input_dim: 3
shuffle: False
action: 'train-set'
formulation: 'space'